services:
    job:
      build: .
      environment:
        - SQLALCHEMY_ECHO=1
        - SQLALCHEMY_DATABASE_URI=postgresql://postgres:password@database/gri
        - DRAMATIQ_BROKER=redis://queue:6379
        # - SQLALCHEMY_DATABASE_URI=mysql+pymysql://root:password@database/gri
      command:
        - python
        - -u
        - cron.py
      depends_on:
        - database
        - queue
    server:
      build: .
      ports:
        - 8080:8080
      environment:
        - WORKERS=1
        - SQLALCHEMY_ECHO=1
        - SQLALCHEMY_DATABASE_URI=postgresql://postgres:password@database/gri
        # - SQLALCHEMY_DATABASE_URI=mysql+pymysql://root:password@database/gri
      command:
        - gunicorn
        - --bind=0.0.0.0:8080
        - run:app
      volumes:
        - ~/certs:/etc/webhook/certs
      depends_on:
        - database
    database:
      image: postgres
      environment:
        - POSTGRES_PASSWORD=password
        - POSTGRES_DB=gri
    queue:
      image: eqalpha/keydb