apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "gri.fullname" . }}-dramatiq
  labels:
    {{- include "gri.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.dramatiq.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "gri.fullname" . }}-dramatiq
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "gri.fullname" . }}-dramatiq
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ include "gri.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - args:
          - tasks
          - --process
          - "2"
          command:
          - dramatiq
          name: {{ .Chart.Name }}
          env:
            {{- range $key, $value := $.Values.env }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          resources:
            {{- toYaml .Values.dramatiq.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
