apiVersion: admissionregistration.k8s.io/v1beta1
kind: MutatingWebhookConfiguration
metadata:
  name: autoresources-gitlab-workloads
  namespace: {{ .Release.Namespace }}
  labels:
    component: mutating-controller
    {{- include "gri.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": "post-install,post-upgrade"
webhooks:
  - name: autoresources.gitlab.workloads
    failurePolicy: Fail
    clientConfig:
      service:
        name: {{ include "gri.fullname" . }}
        namespace: {{ .Release.Namespace }}
        path: /mutate/workloads
      caBundle: {{ .Values.caBundle }} # a base64 encoded self signed ca cert is needed because all Admission Webhooks need to be on SSL
    rules:
      - apiGroups: ["apps", "batch"]
        resources:
          - "*"
        apiVersions:
          - "*"
        operations:
          - CREATE
          - UPDATE
  - name: autoprojects.gitlab.workloads
    failurePolicy: Fail
    clientConfig:
      service:
        name: {{ include "gri.fullname" . }}
        namespace: {{ .Release.Namespace }}
        path: /mutate/namespaces
      caBundle: {{ .Values.caBundle }} # a base64 encoded self signed ca cert is needed because all Admission Webhooks need to be on SSL
    rules:
      - apiGroups:
          - ""
        apiVersions:
          - "*"
        resources:
          - namespaces
        operations:
          - CREATE