apiVersion: admissionregistration.k8s.io/v1beta1
kind: ValidatingWebhookConfiguration
metadata:
  name: autostop-gitlab-workloads
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook": "post-install,post-upgrade,pre-delete"
webhooks:
  - name: autostop.gitlab.workloads
    sideEffects: Some
    failurePolicy: Ignore
    clientConfig:
      service:
        name: {{ include "gri.fullname" . }}
        namespace: {{ .Release.Namespace }}
        path: /autostop/workloads
      caBundle: {{ .Values.caBundle }} # a base64 encoded self signed ca cert is needed because all Admission Webhooks need to be on SSL
    rules:
    - apiGroups:   [""]
      apiVersions: ["v1"]
      operations:  ["CREATE"]
      resources:   ["pods"]
      scope:       "Namespaced"